const root=document.querySelector('#app'),dialog=document.querySelector('#editor');
const schema=await fetch('/schema.json').then(r=>r.json());
let language=localStorage.getItem('mashrooth_language')==='ar'?'ar':'en',user=null,health=null,page='overview',rows=[],cursor=null,history=[null],busy=false,epoch=0,requestId=0,refreshing=null;
const channel=typeof BroadcastChannel==='function'?new BroadcastChannel('mashrooth-session'):null;
const text=(en,ar)=>language==='ar'?ar:en;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=n=>new Intl.NumberFormat(language==='ar'?'ar-SA':'en-SA',{maximumFractionDigits:2}).format(Number(n)||0);
const label=key=>schema[key]?(language==='ar'?schema[key].ar:schema[key].label):({overview:text('Overview','نظرة عامة'),ai:text('AI review','مراجعة ذكية'),members:text('Team members','أعضاء الفريق'),audit:text('Activity audit','سجل النشاط'),settings:text('Workspace settings','إعدادات مساحة العمل')})[key];
const writable=()=>user&&user.role!=='viewer';
const admin=()=>user&&['admin','superadmin'].includes(user.role);
function toast(message){const el=document.querySelector('#notice');el.textContent=message;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.textContent='',6000);}
function brand(){return `<div class="brand"><span class="brand-mark">م</span><span>Mashrooth<small>CONTRACT WORKSPACE</small></span></div>`;}
async function call(path,options={},retry=true){
 const r=await fetch(path,{...options,credentials:'same-origin',headers:{'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(45000)});
 const data=await r.json().catch(()=>({error:'Invalid service response'}));
 if(r.status===401&&retry&&user&&path!=='/api/session'){
   try{refreshing??=call('/api/session',{method:'POST',body:JSON.stringify({action:'refresh'})},false).finally(()=>refreshing=null);await refreshing;return call(path,options,false);}
   catch(e){signedOut();throw e;}
 }
 if(r.status===402){location.assign('/billing');throw new Error('Opening billing');}
 if(!r.ok)throw Object.assign(new Error(data.error||text('Request failed','فشل الطلب')),{status:r.status});
 return data;
}
function signedOut(){epoch++;requestId++;user=null;rows=[];history=[null];cursor=null;busy=false;dialog.close();dialog.replaceChildren();login();}
channel?.addEventListener('message',()=>signedOut());
function setLanguage(){language=language==='en'?'ar':'en';localStorage.setItem('mashrooth_language',language);document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';user?shell():login();}
function login(message=''){
 document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';
 root.innerHTML=`<div class="login"><section class="login-story">${brand()}<div><div class="eyebrow">${text('CLARITY IN EVERY CONTRACT','وضوح في كل عقد')}</div><h1>${text('Your projects.<br>Your obligations.<br>One clear picture.','مشاريعك.<br>التزاماتك.<br>صورة واضحة.')}</h1><p>${text('A shared workspace for the teams building Saudi Arabia. Keep projects, contract records and the next important deadline in view.','مساحة عمل مشتركة لفرق البناء في المملكة. تابع المشاريع والعقود والمواعيد المهمة بوضوح.')}</p></div><footer>© ${new Date().getFullYear()} Mashrooth · CIMS Technologies</footer></section><section class="login-form-wrap"><button class="language ghost">${text('العربية','English')}</button><form id="login"><div class="eyebrow">${text('YOUR WORKSPACE','مساحة العمل')}</div><h2>${text('Welcome back','مرحباً بعودتك')}</h2><p class="muted">${text('Sign in to continue to your organization.','سجّل الدخول إلى مؤسستك.')}</p><div class="field"><label for="email">${text('Work email','البريد الإلكتروني')}</label><input id="email" name="email" type="email" autocomplete="username" required maxlength="254"></div><div class="field"><label for="password">${text('Password','كلمة المرور')}</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="1024"></div><div id="login-error" class="error" role="alert">${esc(message)}</div><button class="primary" type="submit">${text('Sign in →','تسجيل الدخول ←')}</button><p class="hint">${text('Access is provisioned by your workspace administrator. Contact them for an invitation or password recovery.','تُمنح صلاحية الدخول من مسؤول مساحة العمل. تواصل معه للحصول على دعوة أو استعادة كلمة المرور.')}</p><p><a href="/trial">${text('Start a 14-day trial','ابدأ تجربة لمدة ١٤ يوماً')}</a></p><hr class="divider"><p class="hint">${text('Your contract records are loaded only after your organization access is verified.','تُحمّل سجلات العقود بعد التحقق من صلاحية الوصول إلى مؤسستك.')}</p></form></section></div>`;
 root.querySelector('.language').onclick=setLanguage;
 root.querySelector('#login').onsubmit=async e=>{e.preventDefault();const form=e.target,btn=form.querySelector('button[type=submit]');btn.disabled=true;document.querySelector('#login-error').textContent='';
  try{const data=await call('/api/session',{method:'POST',body:JSON.stringify({action:'login',email:form.email.value,password:form.password.value})},false);form.password.value='';channel?.postMessage('session-changed');user=data.user;epoch++;page='overview';shell();}
  catch(err){document.querySelector('#login-error').textContent=err.message;form.password.value='';}finally{btn.disabled=false;}};
}
function shell(){
 if(!user)return login();
 call('/api/billing/status').then(b=>{if(!b.entitled)location.assign('/billing');else if(b.status==='trialing'){const days=Math.max(0,Math.ceil((Date.parse(b.trialEndsAt)-Date.now())/86400000));const el=document.createElement('div');el.className='banner';el.textContent=text('Trial: '+days+' days left.','التجربة: '+days+' أيام متبقية.');document.querySelector('#main')?.before(el);}}).catch(e=>toast(e.message));
 document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';
 const pages=['overview',...Object.keys(schema),'ai',...(admin()?['members','audit']:[]),'settings'];
 root.innerHTML=`<div class="shell"><aside class="sidebar">${brand()}<nav class="nav" aria-label="${text('Main navigation','التنقل الرئيسي')}">${pages.map(p=>`<button data-page="${p}" class="${page===p?'active':''}" ${page===p?'aria-current="page"':''}><span class="nav-icon">${p==='overview'?'◈':p==='ai'?'✧':p==='settings'?'⚙':'◇'}</span>${esc(label(p))}</button>`).join('')}</nav><footer>${text('Organization access','صلاحيات المؤسسة')}<br>${esc(user.role)} · ${text('Private workspace','مساحة عمل خاصة')}</footer></aside><div class="main-wrap"><header class="topbar"><div><span class="workspace-label">${text('Workspace','مساحة العمل')}</span><strong>${esc(user.organization)}</strong></div><div class="top-actions"><span class="avatar">${esc(user.name?.slice(0,2).toUpperCase())}</span><a href="/billing">${text('Billing','الفوترة')}</a><button id="language" class="ghost">${text('العربية','English')}</button><button id="logout" class="ghost">${text('Sign out','تسجيل الخروج')}</button></div></header><main id="main" class="content" tabindex="-1"></main></div></div>`;
 root.querySelectorAll('[data-page]').forEach(btn=>btn.onclick=()=>{page=btn.dataset.page;history=[null];cursor=null;rows=[];shell();});
 root.querySelector('#language').onclick=setLanguage;
 root.querySelector('#logout').onclick=async()=>{try{await call('/api/session',{method:'POST',body:JSON.stringify({action:'logout'})},false);}catch(e){toast(e.message);}finally{channel?.postMessage('signed-out');signedOut();}};
 load();
}
function heading(sub='',actions=''){return `<div class="page-heading"><div><div class="eyebrow">MASHROOTH / ${esc(label(page))}</div><h1>${esc(label(page))}</h1><p>${sub}</p></div><div class="row">${actions}</div></div>`;}
async function load(){
 const main=document.querySelector('#main'),id=++requestId,currentEpoch=epoch;
 main.innerHTML=heading()+`<div class="card" role="status">${text('Loading your workspace…','جارٍ تحميل مساحة العمل…')}</div>`;
 try{
  if(page==='overview'){const data=await call('/api/overview');if(id!==requestId||currentEpoch!==epoch)return;main.innerHTML=overview(data);main.querySelector('#view-obligations').onclick=()=>{page='obligations';shell();};}
  else if(schema[page]){const data=await call('/api/records?collection='+page+(history.at(-1)?'&cursor='+encodeURIComponent(history.at(-1)):''));if(id!==requestId||currentEpoch!==epoch)return;rows=data.data;cursor=data.nextCursor;renderRecords();}
  else if(page==='members'){const data=await call('/api/admin/users');if(id!==requestId||currentEpoch!==epoch)return;members(data.users);}
  else if(page==='audit'){const data=await call('/api/audit');if(id!==requestId||currentEpoch!==epoch)return;audit(data.data);}
  else {health=await fetch('/api/health',{cache:'no-store'}).then(r=>r.json());if(id!==requestId||currentEpoch!==epoch)return;page==='ai'?ai():settings();}
 }catch(err){if(id!==requestId||currentEpoch!==epoch)return;main.innerHTML=heading()+`<div class="empty"><strong>${text('Could not load this page','تعذر تحميل الصفحة')}</strong><p>${esc(err.message)}</p><button id="retry">${text('Try again','حاول مرة أخرى')}</button></div>`;main.querySelector('#retry').onclick=load;}
}
function overview(d){
 const ratio=d.totalValue?Math.round(d.localValue/d.totalValue*100):0;
 return heading(text('The latest records and priorities across your organization.','آخر السجلات والأولويات في مؤسستك.'),`<span class="tag">${text('Live workspace data','بيانات مساحة العمل')}</span>`)+`<section class="stats">${[[d.projects,text('Projects','المشاريع'),text('Registered in this workspace','مسجلة في مساحة العمل')],[d.contracts,text('Contracts','العقود'),text('Contract register','سجل العقود')],[d.risks,text('Open risks','المخاطر المفتوحة'),text('Needs monitoring or mitigation','تحتاج إلى متابعة أو معالجة')],[d.overdue,text('Overdue obligations','التزامات متأخرة'),text('Review with the responsible owner','راجعها مع الشخص المسؤول')]].map(([n,l,h])=>`<article class="stat"><span>${l}</span><strong>${number(n)}</strong><small>${h}</small></article>`).join('')}</section><div class="grid-two"><section class="card"><div class="row" style="justify-content:space-between"><h2>${text('Next obligations','الالتزامات القادمة')}</h2><button class="small" id="view-obligations">${text('View register →','عرض السجل ←')}</button></div>${d.upcoming.length?`<div class="table-wrap"><table><thead><tr><th>${text('Obligation','الالتزام')}</th><th>${text('Due date','الاستحقاق')}</th><th>${text('Owner','المسؤول')}</th></tr></thead><tbody>${d.upcoming.map(o=>`<tr><td>${esc(o.title)}<small>${esc(o.source_reference)}</small></td><td class="nowrap">${esc(o.due_date)}</td><td>${esc(o.owner||'—')}</td></tr>`).join('')}</tbody></table></div>`:`<p class="muted">${text('No open obligations. Add a contract reference, owner and due date to start tracking.','لا توجد التزامات مفتوحة. أضف المرجع التعاقدي والمسؤول وتاريخ الاستحقاق.')}</p>`}<p class="hint">${text('Dates are entered by your team. Review notice requirements against the signed contract. Email reminders are not enabled.','يدخل فريقك التواريخ. راجع متطلبات الإشعار وفقاً للعقد الموقع. التذكيرات البريدية غير مفعّلة.')}</p></section><section class="card"><div class="eyebrow">${text('LOCAL CONTENT RECORDS','سجلات المحتوى المحلي')}</div><h2>${text('Recorded local spend','الإنفاق المحلي المسجل')}</h2><strong class="value-large">${number(ratio)}<span class="muted">%</span></strong><div class="meter"><progress max="100" value="${Math.max(0,Math.min(100,ratio))}" aria-label="Local spend percentage"></progress></div><p class="hint">${number(d.localValue)} / ${number(d.totalValue)} SAR</p><hr class="divider"><p class="hint">${text('Simple local / total spend ratio from your records. This is not a certified LCGPA score or tender eligibility assessment.','نسبة الإنفاق المحلي إلى الإجمالي من سجلاتك. ليست درجة معتمدة من هيئة المحتوى المحلي أو تقييماً لأهلية المناقصة.')}</p></section></div><section class="card"><div class="row"><div><div class="eyebrow">${text('CONTRACT REGISTER VALUE','قيمة سجل العقود')}</div><h2>${number(d.contractValue)} SAR</h2></div><p class="muted">${text('Open claims','المطالبات المفتوحة')}: ${number(d.claims)}</p></div></section>`;
}
function columns(){const config=schema[page];return [config.name,...Object.keys(config.fields).filter(k=>k!==config.name&&!['textarea','document'].includes(config.fields[k][2]))].slice(0,5);}
function renderRecords(){
 const main=document.querySelector('#main');
 main.innerHTML=heading(text('Changes are saved to your organization after server confirmation.','تُحفظ التغييرات في مؤسستك بعد تأكيد الخادم.'),`${writable()?`<button id="add" class="primary">+ ${text('Add record','إضافة سجل')}</button>`:''}`)+
 `${page==='document_contents'?`<div class="banner">${text('PDF, DOCX and TXT text extraction · Maximum 3 MB / 100 PDF pages. Original files are not stored. Scanned pages need OCR before uploading.','استخراج نصوص PDF وDOCX وTXT · الحد الأقصى ٣ ميجابايت / ١٠٠ صفحة PDF. لا تُخزن الملفات الأصلية. الصفحات الممسوحة تحتاج إلى OCR.')}</div>`:''}<div class="toolbar"><input id="filter" type="search" aria-label="${text('Filter this page','تصفية هذه الصفحة')}" placeholder="${text('Filter this page…','تصفية هذه الصفحة…')}"><div class="row"><button id="export">${text('Export page','تصدير الصفحة')}</button><button id="reload">${text('Refresh','تحديث')}</button></div></div><div id="record-table"></div><div class="pager"><span>${text('Page','الصفحة')} ${history.length} · ${number(rows.length)} ${text('records','سجلات')}</span><div class="row"><button id="previous" ${history.length===1?'disabled':''}>${text('Previous','السابق')}</button><button id="next" ${!cursor?'disabled':''}>${text('Next','التالي')}</button></div></div>`;
 function table(){const q=main.querySelector('#filter').value.toLowerCase();const filtered=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q));const cols=columns();
  main.querySelector('#record-table').innerHTML=filtered.length?`<div class="table-wrap"><table><thead><tr>${cols.map(k=>`<th>${esc(k==='id'?text('Document ID','رقم المستند'):schema[page].fields[k]?.[language==='ar'?1:0]||k)}</th>`).join('')}<th>${text('Actions','الإجراءات')}</th></tr></thead><tbody>${filtered.map(r=>`<tr>${cols.map((k,i)=>`<td>${esc(typeof r[k]==='number'?number(r[k]):r[k]||'—')}${i===0?`<small>${esc(r.id)}</small>`:''}</td>`).join('')}<td class="nowrap"><button class="small" data-edit="${esc(r.id)}">${writable()?text('Edit','تعديل'):text('View','عرض')}</button> ${writable()?`<button class="small danger" data-delete="${esc(r.id)}">${text('Delete','حذف')}</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:`<div class="empty"><strong>${text('No records to display','لا توجد سجلات لعرضها')}</strong><p>${q?text('Try another filter.','جرّب تصفية أخرى.'):text('Add the first record to build your organization’s register.','أضف أول سجل لبناء سجل مؤسستك.')}</p></div>`;
  main.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(rows.find(r=>r.id===b.dataset.edit)));
  main.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(rows.find(r=>r.id===b.dataset.delete)));
 }
 table();main.querySelector('#filter').oninput=table;main.querySelector('#reload').onclick=load;
 main.querySelector('#add')?.addEventListener('click',()=>edit());
 main.querySelector('#export').onclick=()=>{const a=document.createElement('a');const u=URL.createObjectURL(new Blob([JSON.stringify(rows.map(({row_id,...r})=>r),null,2)],{type:'application/json'}));a.href=u;a.download=page+'-page-'+history.length+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
 main.querySelector('#previous').onclick=()=>{history.pop();load();};main.querySelector('#next').onclick=()=>{history.push(cursor);load();};
}
function edit(record){
 const config=schema[page],collection=page;const readOnly=!writable();
 dialog.innerHTML=`<form id="record-form"><div class="dialog-heading"><h2 id="editor-title">${record?text('Record details','تفاصيل السجل'):text('Add record','إضافة سجل')}</h2><button type="button" id="close" class="ghost" aria-label="Close">✕</button></div>${record?`<p class="hint">${esc(record.id)} · ${text('Version','الإصدار')} ${record.version}</p>`:''}${collection==='document_contents'&&!readOnly?`<div class="field wide"><label for="document-file">${text('Extract from a file','استخراج النص من ملف')}</label><input type="file" id="document-file" accept=".txt,.pdf,.docx"><p class="hint" id="file-status"></p></div>`:''}<div class="form-grid">${Object.entries(config.fields).map(([k,f])=>{const type=f[2],v=record?.[k]??'';return `<div class="field ${['textarea','document'].includes(type)?'wide':''}"><label for="field-${k}">${esc(f[language==='ar'?1:0])}${f[3]?' *':''}</label>${Array.isArray(type)?`<select id="field-${k}" name="${k}" ${readOnly?'disabled':''}>${type.map(x=>`<option ${x===v?'selected':''} value="${esc(x)}">${esc(x)}</option>`).join('')}</select>`:['textarea','document'].includes(type)?`<textarea id="field-${k}" name="${k}" maxlength="${type==='document'?750000:10000}" ${f[3]?'required':''} ${readOnly?'readonly':''}>${esc(v)}</textarea>`:`<input id="field-${k}" name="${k}" type="${['number','percent','integer','score'].includes(type)?'number':type}" value="${esc(v)}" ${f[3]?'required':''} ${readOnly?'readonly':''} ${['number','percent','integer','score'].includes(type)?`min="${type==='score'?1:0}" step="${['integer','score'].includes(type)?1:'0.01'}" max="${type==='percent'?100:type==='score'?5:1e14}"`:'maxlength="500"'}>`}</div>`;}).join('')}</div><div id="form-error" class="error" role="alert"></div><div class="dialog-actions"><button type="button" id="cancel">${text('Close','إغلاق')}</button>${!readOnly?`<button type="submit" class="primary">${text('Save record','حفظ السجل')}</button>`:''}</div></form>`;
 dialog.showModal();dialog.querySelector('#close').onclick=()=>dialog.close();dialog.querySelector('#cancel').onclick=()=>dialog.close();
 dialog.querySelector('#document-file')?.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const status=dialog.querySelector('#file-status'),save=dialog.querySelector('[type=submit]');if(file.size>3000000){status.textContent=text('Maximum file size is 3 MB','الحد الأقصى للملف ٣ ميجابايت');return;}save.disabled=true;status.textContent=text('Extracting text…','جارٍ استخراج النص…');try{const content=await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result.split(',')[1]);fr.onerror=reject;fr.readAsDataURL(file);});const data=await call('/api/parse',{method:'POST',body:JSON.stringify({content,name:file.name})});dialog.querySelector('[name=content]').value=data.text;status.textContent=file.name+' · '+number(data.chars)+' '+text('characters','حرف');}catch(e){status.textContent=e.message;}finally{save.disabled=false;}});
 dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();if(readOnly||busy)return;const form=e.target,values={};for(const[k,f]of Object.entries(config.fields)){const v=form.elements[k].value;values[k]=['number','percent','integer','score'].includes(f[2])?(v===''?null:Number(v)):v;}
  busy=true;form.querySelector('[type=submit]').disabled=true;const session=epoch;
  try{await call('/api/records?collection='+collection,{method:record?'PATCH':'POST',body:JSON.stringify({id:record?.id||crypto.randomUUID(),version:record?.version,values})});if(session!==epoch)return;dialog.close();toast(text('Saved to your workspace','تم الحفظ في مساحة العمل'));load();}
  catch(err){if(session===epoch)dialog.querySelector('#form-error').textContent=err.message;}
  finally{busy=false;if(form.isConnected)form.querySelector('[type=submit]').disabled=false;}};
}
function remove(record){
 const collection=page;
 dialog.innerHTML=`<h2 id="editor-title">${text('Delete this record?','هل تريد حذف هذا السجل؟')}</h2><p>${esc(record[schema[page].name])}</p><p class="hint">${text('This removes the record from the organization. A project with linked records cannot be deleted.','سيُحذف السجل من المؤسسة. لا يمكن حذف مشروع يحتوي على سجلات مرتبطة.')}</p><div id="delete-error" class="error" role="alert"></div><div class="dialog-actions"><button id="cancel">${text('Cancel','إلغاء')}</button><button id="confirm" class="danger">${text('Delete record','حذف السجل')}</button></div>`;dialog.showModal();dialog.querySelector('#cancel').onclick=()=>dialog.close();dialog.querySelector('#confirm').onclick=async e=>{e.target.disabled=true;try{await call('/api/records?collection='+collection,{method:'DELETE',body:JSON.stringify({id:record.id,version:record.version})});dialog.close();toast(text('Record deleted','تم حذف السجل'));load();}catch(err){dialog.querySelector('#delete-error').textContent=err.message;}finally{e.target.disabled=false;}};
}
function members(data){
 const rank={viewer:0,manager:1,admin:2,superadmin:3};
 document.querySelector('#main').innerHTML=heading(text('Roles are enforced by the database. New members require verified provisioning.','تُطبق الأدوار في قاعدة البيانات. الأعضاء الجدد يحتاجون إلى تزويد موثق.'))+`<div class="table-wrap"><table><thead><tr><th>${text('Member','العضو')}</th><th>${text('Email','البريد')}</th><th>${text('Role','الدور')}</th></tr></thead><tbody>${data.map(m=>`<tr><td>${esc(m.name||m.id)}</td><td>${esc(m.email)}</td><td>${m.id!==user.id&&rank[m.role]<rank[user.role]?`<select aria-label="Role for ${esc(m.email)}" data-member="${esc(m.id)}">${Object.keys(rank).filter(r=>rank[r]<rank[user.role]).map(r=>`<option ${r===m.role?'selected':''}>${r}</option>`).join('')}</select>`:`<span class="tag">${esc(m.role)}</span>`}</td></tr>`).join('')}</tbody></table></div><p class="hint">${text('Maximum 200 members shown. Additional top-level administrators and offboarding are managed through the authorized database operator.','يُعرض ٢٠٠ عضو كحد أقصى. يُدار المسؤولون الإضافيون وإلغاء الوصول بواسطة مشغل قاعدة البيانات المعتمد.')}</p>`;
 document.querySelectorAll('[data-member]').forEach(s=>s.onchange=async()=>{s.disabled=true;try{await call('/api/admin/users',{method:'PATCH',body:JSON.stringify({userId:s.dataset.member,role:s.value})});toast(text('Role updated','تم تحديث الدور'));load();}catch(e){toast(e.message);load();}});
}
function audit(data){document.querySelector('#main').innerHTML=heading(text('The latest 100 record changes, recorded by the database.','آخر ١٠٠ تغيير على السجلات كما سجلتها قاعدة البيانات.'))+`<div class="table-wrap"><table><thead><tr><th>${text('Time','الوقت')}</th><th>${text('Action','الإجراء')}</th><th>${text('Register','السجل')}</th><th>${text('Record / actor','السجل / المنفذ')}</th></tr></thead><tbody>${data.map(r=>`<tr><td>${esc(new Date(r.created_at).toLocaleString(language==='ar'?'ar-SA':'en-GB'))}</td><td>${esc(r.action)}</td><td>${esc(label(r.collection_name)||r.collection_name)}</td><td>${esc(r.record_id)}<small>${esc(r.actor_id)}</small></td></tr>`).join('')}</tbody></table></div>`;}
function settings(){document.querySelector('#main').innerHTML=heading(text('Your access and service availability.','صلاحياتك وتوفر الخدمات.'))+`<section class="card"><h2>${text('Organization','المؤسسة')}</h2><dl class="definition"><dt>${text('Workspace','مساحة العمل')}</dt><dd>${esc(user.organization)}</dd><dt>${text('Signed in as','مسجّل الدخول باسم')}</dt><dd>${esc(user.email)}</dd><dt>${text('Role','الدور')}</dt><dd>${esc(user.role)}</dd><dt>${text('Database','قاعدة البيانات')}</dt><dd>${esc(health.services?.database||'unavailable')}</dd><dt>${text('AI provider','مزود الذكاء الاصطناعي')}</dt><dd>${esc(health.services?.ai||'disabled')}</dd></dl></section><div class="banner">${text('This release supports an administrator-provisioned pilot. Billing status is available on the Billing page. Email reminders and government API connectors are not active. Data and AI processing locations have not been verified for residency claims.','يدعم هذا الإصدار تجربة يوفرها المسؤول. التسجيل الذاتي والاشتراكات المدفوعة والتذكيرات البريدية وربط الجهات الحكومية غير مفعّلة. لم يتم التحقق من مواقع معالجة البيانات والذكاء الاصطناعي لأغراض الإقامة.')}</div><section class="card"><h2>${text('Data and exports','البيانات والتصدير')}</h2><p class="muted">${text('Records are held in memory during this session. Use Export page in a register to download the currently displayed records. Ask your administrator for a complete database export, retention request or account recovery.','تُحفظ السجلات في الذاكرة أثناء الجلسة. استخدم تصدير الصفحة لتنزيل السجلات المعروضة. اطلب من المسؤول تصديراً كاملاً أو طلب احتفاظ أو استعادة حساب.')}</p></section>`;}
function ai(){
 const enabled=health.services?.ai==='configured'&&writable();
 document.querySelector('#main').innerHTML=heading(text('A draft review of the text you choose to submit.','مراجعة أولية للنص الذي تختار إرساله.'))+`<div class="banner">${text('Analysis is sent to the configured external AI provider. Remove unnecessary personal or confidential material. Verify every finding and citation against the signed document.','يُرسل التحليل إلى مزود الذكاء الاصطناعي الخارجي المهيأ. أزل البيانات الشخصية أو السرية غير اللازمة. تحقق من كل نتيجة ومرجع وفقاً للمستند الموقع.')}</div><section class="card"><form id="ai-form"><label for="ai-text">${text('Contract text','نص العقد')}</label><textarea id="ai-text" rows="13" maxlength="45000" required ${!enabled?'disabled':''}></textarea><p class="hint">${enabled?text('Provide a focused passage. The AI cannot access other records in your workspace.','قدّم مقطعاً محدداً. لا يستطيع الذكاء الاصطناعي الوصول إلى السجلات الأخرى.'):text('AI is disabled or your role is read-only. Your text will not be submitted.','الذكاء الاصطناعي غير مفعّل أو صلاحيتك للقراءة فقط. لن يُرسل النص.')}</p><button type="submit" class="primary" ${!enabled?'disabled':''}>${text('Review text','مراجعة النص')}</button><p id="ai-error" class="error" role="alert"></p></form></section><section id="ai-result" class="card" hidden><h2>${text('Draft · Human review required','مسودة · تتطلب مراجعة بشرية')}</h2><pre class="output"></pre></section>`;
 document.querySelector('#ai-form').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('button');btn.disabled=true;const session=epoch,current=requestId;try{const data=await call('/api/ai/analyze',{method:'POST',body:JSON.stringify({messages:[{role:'user',content:document.querySelector('#ai-text').value}]})});if(session!==epoch||current!==requestId)return;document.querySelector('#ai-result').hidden=false;document.querySelector('#ai-result pre').textContent=(data.content||[]).filter(b=>b.type==='text').map(b=>b.text).join('\n');}catch(err){if(session===epoch&&current===requestId)document.querySelector('#ai-error').textContent=err.message;}finally{btn.disabled=false;}};
}
// Never read the old app's shared contract cache or browser-stored sessions.
try{let session;try{session=await call('/api/session',{},false);}catch(e){if(e.status!==401)throw e;session=await call('/api/session',{method:'POST',body:JSON.stringify({action:'refresh'})},false);}user=session.user;shell();}
catch(e){login(e.status===401?'':e.message);}
